### ISSUE TITLE
IPFS.Blockfrost.dev - Images not showing up

### ISSUE THREAD

**Issue by aussiegingersnap** [SmaugPool/pool.pm#15]
We have a recent mint that is still not pulling images for all our content with IPFS links using the IPFS.Blockfrost.dev/IPFS/{IPFS-hash}convention in our metadata. Here is an example transaction id - any guidance would be appreciated on this!

https://cardanoscan.io/transaction/ff5a39a222cc74574fdcf12c14e7888d253ee703d4f6f1a126de5b3b5d896f7f?tab=metadata

**Comment by aussiegingersnap** [comment]
What's wrong with this? 
![image](https://user-images.githubusercontent.com/66174470/139517644-428d9a0d-69ff-4973-9a82-1d9b6e5e00ca.png)

**Comment by SmaugPool** [comment]
The `location` property is not part of CIP 25 and is therefore not used.

The `image` property uses an HTTP link which is not supported and will likely never be because it removes the benefits of a decentralized network.

For now only IPFS and data URLs are supported in `image` property, for example:
```
"image": "ipfs://QmQWKqnUKN1fuLAHVTY5skVqg4pGhNmHWLncWDaqB9vMx9"
```

Note that you can look at any CNFT metadata using the technique described here:
https://twitter.com/pool_pm/status/1431755548664401921?s=20
