### ISSUE TITLE
Tokens without 721 metadata are not displayed on tokens page

### ISSUE THREAD

**Issue by frog357** [SmaugPool/pool.pm#41]
I am experiencing a problem where our token seems to be blocked from display on the /tokens page. I have tested multiple ways - by sending from an enterprise wallet to a Daedalus user, by sending from Daedalus to another user using Daedalus- at no time was this a transaction which was from one wallet to the same wallet. I also burned this token on multiple occasions expecting it to be visible - again it never shows up - we try this at all times of the day - it's not a load issue or number of tokens displayed thing.

https://pool.pm/asset1rew6h8056v6zc5kzdgc9t59vxx5m44czpmqs25

**Comment by SmaugPool** [comment]
Currently, only tokens with a CIP 25 721 metadata are displayed on pool.pm/tokens page.

It seems your token does not have a 721 metadata and is therefore not displayed.

In the future, tokens without images or with just Token Registry images could be displayed again, but this will require some filter or to split the page between NFTs/FTs because they were too many of them and the page is currently more NFT oriented.

**Comment by SmaugPool** [comment]
All tokens should not be displayed again, so your should be included too (unless it's part of intra-wallet transactions).

I will add a filter button later to clean up the page for NFT users.

Please reopen if you think the issue is not solved.
